### PR TITLE
Translation for Japanese

### PR DESCRIPTION
**Pull request by arcoyk**

### CODE REVIEW

**Comment by arcoyk** [comment]
@naotaro0123 Can you come up with any reason why checks fail? Thanks!

**Comment by greggman** [comment]
if you remove `package-lock.json` from your PR it should pass the checks

**Comment by greggman** [comment]
deleting the file in the PR deletes the file from the repo. you need to **remove** the file from the PR

There are many ways to fix.

Here's one. On your local machine try

```
git reset HEAD~3
git add threejs/lessons/ja/threejs-custom-geometry.md 
git commit -m "Japanese translation of custom geometry"
git add threejs/lessons/ja/threejs-rendertargets.md 
git commit -m "Japanese translation of custom geometry"
git push --force origin:ja
```

**Comment by greggman** [comment]
Never mind. I committed them myself by hand

**Pull request closed without merging**
