### PR TITLE
translate 4 chapters: cameras; 2optimize; rendering on demand

### PR DESCRIPTION
**Pull request by Roy-Kid**
I have finished translate the 4 chapters but i can not build it because:
/Users/roy/work/threejsfundamentals/node_modules/ld-check-dependencies/index.js:4
  return result.added.length > 0 || result.updated.length > 0 || result.removed > 0;
                                                   ^

TypeError: Cannot read property 'length' of undefined
    at dependenciesNeedUpdating (/Users/roy/work/threejsfundamentals/node_modules/ld-check-dependencies/index.js:4:52)
    at Object.<anonymous> (/Users/roy/work/threejsfundamentals/node_modules/ld-check-dependencies/bin/ld-check-dependencies:6:5)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

### CODE REVIEW

**Comment by greggman** [comment]
You can try building with `npm run build-ci`

Also though, I just updated to `r125` so could you please search and replace `r122` with `r125` in these files? If not I can do it myself.

**Comment by Roy-Kid** [comment]
Sorry, I ran the npm run build-ci, but an error raise. It said cannot find module '../build/Release/canvas.node'. I don't know how to debug it because I have little frontend experience. Could you please merge the translated script manually? 

PS: I just simply replace the English script with Chinese....

**Comment by greggman** [comment]
Sigh....You searched and replace r122 with r125 across all files, that's not what I needed you to do. I needed you to just search and replace r122 with r125 on the 5 files you changed 🙁

**Comment by greggman** [comment]
I will do it manually

**Comment by greggman** [comment]
merged https://github.com/gfxfundamentals/threejsfundamentals/commit/5489caf1cdfca35b2710827e62255e1474c398f2

**Pull request closed without merging**
